<?php
$sql ="
SELECT  
	(tanggal),
	(proses),
	(shift),
	(item_proses),
	(tipe),
	(satuan),
	sum(IF(DAY(tanggal) = 1, jumlah, 0)) AS jumlah_1,
	sum(IF(DAY(tanggal) = 2, jumlah, 0)) AS jumlah_2,
	sum(IF(DAY(tanggal) = 3, jumlah, 0)) AS jumlah_3,
	sum(IF(DAY(tanggal) = 4, jumlah, 0)) AS jumlah_4,
	sum(IF(DAY(tanggal) = 5, jumlah, 0)) AS jumlah_5,
	sum(IF(DAY(tanggal) = 6, jumlah, 0)) AS jumlah_6,
	sum(IF(DAY(tanggal) = 7, jumlah, 0)) AS jumlah_7,
	sum(IF(DAY(tanggal) = 8, jumlah, 0)) AS jumlah_8,
	sum(IF(DAY(tanggal) = 9, jumlah, 0)) AS jumlah_9,
	sum(IF(DAY(tanggal) = 10, jumlah, 0)) AS jumlah_10,
	sum(IF(DAY(tanggal) = 11, jumlah, 0)) AS jumlah_11,
	sum(IF(DAY(tanggal) = 12, jumlah, 0)) AS jumlah_12,
	sum(IF(DAY(tanggal) = 13, jumlah, 0)) AS jumlah_13,
	sum(IF(DAY(tanggal) = 14, jumlah, 0)) AS jumlah_14,
	sum(IF(DAY(tanggal) = 15, jumlah, 0)) AS jumlah_15,
	sum(IF(DAY(tanggal) = 16, jumlah, 0)) AS jumlah_16,
	sum(IF(DAY(tanggal) = 17, jumlah, 0)) AS jumlah_17,
	sum(IF(DAY(tanggal) = 18, jumlah, 0)) AS jumlah_18,
	sum(IF(DAY(tanggal) = 19, jumlah, 0)) AS jumlah_19,
	sum(IF(DAY(tanggal) = 20, jumlah, 0)) AS jumlah_20,
	sum(IF(DAY(tanggal) = 21, jumlah, 0)) AS jumlah_21,
	sum(IF(DAY(tanggal) = 22, jumlah, 0)) AS jumlah_22,
	sum(IF(DAY(tanggal) = 23, jumlah, 0)) AS jumlah_23,
	sum(IF(DAY(tanggal) = 24, jumlah, 0)) AS jumlah_24,
	sum(IF(DAY(tanggal) = 25, jumlah, 0)) AS jumlah_25,
	sum(IF(DAY(tanggal) = 26, jumlah, 0)) AS jumlah_26,
	sum(IF(DAY(tanggal) = 27, jumlah, 0)) AS jumlah_27,
	sum(IF(DAY(tanggal) = 28, jumlah, 0)) AS jumlah_28,
	sum(IF(DAY(tanggal) = 29, jumlah, 0)) AS jumlah_29,
	sum(IF(DAY(tanggal) = 30, jumlah, 0)) AS jumlah_30,
	sum(IF(DAY(tanggal) = 31, jumlah, 0)) AS jumlah_31,
	sum(IF(MONTH(tanggal) = '$bln', jumlah, 0)) AS jumlah_Total
FROM `plan_produksi` WHERE MONTH(tanggal)= '$bln' AND YEAR(tanggal)= '$thn' GROUP BY proses, shift
";
?>